### ISSUE TITLE
awating sleep

### ISSUE THREAD

**Issue by dimdenGD** [AnIdiotsGuide/discordjs-bot-guide#104]
In [Tracking used invites](https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/tracking-used-invites.md) there's this snippet of code

```js
// Initialize the invite cache
const invites = {};

// A pretty useful method to create a delay without blocking the whole script.
const wait = require('util').promisify(setTimeout);

client.on('ready', () => {
  // "ready" isn't really ready. We need to wait a spell.
  wait(1000);

  // Load all invites for all guilds and save them to the cache.
  client.guilds.forEach(g => {
    g.fetchInvites().then(guildInvites => {
      invites[g.id] = guildInvites;
    });
  });
});
```
And I don't understand why `wait(1000)` function is being used without `await`, I think it doesn't do anything without awaiting for it..

**Comment by eslachance** [comment]
You're correct, that was a mistake, I've corrected the guide. Thanks!
