### ISSUE TITLE
uses is not defined

### ISSUE THREAD

**Issue by arjellel** [AnIdiotsGuide/discordjs-bot-guide#106]
When uses is  uses < 2 it will get this error for some reason that i cant figure out?
error :  uses is not defined

**Comment by JesseBS2** [comment]
Yo I suggest being a bit more specific,
I screenshot of the error would be helpful, also a screenshot/block of your code would help out a lot,

**Comment by YorkAARGH** [comment]
> When uses is uses < 2 it will get this error for some reason that i cant figure out?
> error : uses is not defined

This is due to single use invites being generated, just check if the thing has uses, if it doesn't then return.
