### ISSUE TITLE
i found a error 

### ISSUE THREAD

**Issue by shivamthakkar** [AnIdiotsGuide/discordjs-bot-guide#107]
when i joined my server i receive a error in console and that is 
![image](https://user-images.githubusercontent.com/51533539/82171732-d95e7380-98e5-11ea-9a57-ce52e5bb67e0.png)

**Comment by MutantRabbit767** [comment]
same here

**Comment by arjellel** [comment]
On the latest version of the discord that is v12 u need to cache it... do that and it will work

**Comment by TheTexasDev** [comment]
This guide is a little outdated, in discord.js Version 12; `client.guilds.forEach` should be replaced with `client.guilds.cache.forEach`

**Comment by ForSomeCodezYT** [comment]
How to run the embed, What is the prefix

**Comment by YorkAARGH** [comment]
> This guide is a little outdated, in discord.js Version 12; `client.guilds.forEach` should be replaced with `client.guilds.cache.forEach`

Yeah, this is true. We're getting that resolved over time ^_^

> How to run the embed, What is the prefix

Not sure what you're asking but I'm pretty sure this is the wrong place.
