### ISSUE TITLE
Update raw-events.md

### ISSUE THREAD

**Issue by mrsolarius** [AnIdiotsGuide/discordjs-bot-guide#114]
the raw events script for the emoji event handle is realy useful but since discordjs 12 he no work anymore. So it's possible to update it 😊🤞?
Best Regards

**Comment by YorkAARGH** [comment]
We're still in the process of updating the guide to version 12, hopefully it'll be done soon.

**Comment by mrsolarius** [comment]
Cool, I can't wait.^^
So I wait your push and I close that issue ;)
