### ISSUE TITLE
Please update this guide 

### ISSUE THREAD

**Issue by Matin-A** [AnIdiotsGuide/discordjs-bot-guide#116]
Starting Discord.js 12 `client.users`, `client.guilds`, `client.channels`, `guild.channels`, `guild.members` are now a Manager instead of a Collection, so you can't use `Collection.get(id)` for them.

However you could use `client.users.cache`, `client.guilds.cache`, `client.channels.cache`, `guild.channels.cache`, `guild.members.cache` instead.

Please update this guide: https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/understanding/collections.md
Edit: See https://discordjs.guide/additional-info/changes-in-v12.html

**Comment by NairodTV** [comment]
```
client.on('raw', packet => {
    if (!['MESSAGE_REACTION_ADD', 'MESSAGE_REACTION_REMOVE'].includes(packet.t)) return;
    const channel = client.channels.cache.get(packet.d.channel_id);
    if (channel.messages.cache.has(packet.d.message_id)) return;
    channel.messages.fetch(packet.d.message_id).then(message => {
        const emoji = packet.d.emoji.id ? `${packet.d.emoji.name}:${packet.d.emoji.id}` : packet.d.emoji.name;
        const reaction = message.reactions.cache.get(emoji);
        if (reaction) reaction.users.cache.set(packet.d.user_id, client.users.cache.get(packet.d.user_id));
        if (packet.t === 'MESSAGE_REACTION_ADD') {
            client.emit('messageReactionAdd', reaction, client.users.cache.get(packet.d.user_id));
        }
        if (packet.t === 'MESSAGE_REACTION_REMOVE') {
            client.emit('messageReactionRemove', reaction, client.users.cache.get(packet.d.user_id));
        }
    });
});
```
Here is the updated version for v12.

**Comment by YorkAARGH** [comment]
If you look in the top left of the guide's website, there is a drop down selector where you can select version 12.
