### ISSUE TITLE
It replies more than once

### ISSUE THREAD

**Issue by RayZ3R0** [AnIdiotsGuide/discordjs-bot-guide#123]
why does it reply 2-5 times or more.
![image](https://user-images.githubusercontent.com/69317757/93482431-86430e80-f921-11ea-949f-ef7a8dbfde4a.png)

**Comment by kashalls** [comment]
You might have more than one instance of your discord bot launched. Make sure you don't have 4 bots in the background.

**Comment by Pranay0302** [comment]
the problem with this is that, @RayZ3R0 you would have run the bot more than once so in order to stop it, just kill the PID of the extra ones that you are running

**Comment by eslachance** [comment]
This repository is for updates and suggestions about the guide, not for tech support. For technical support please join our Discord Guild: [https://discord.gg/4NE4bk7](https://discord.gg/4NE4bk7)
