### ISSUE TITLE
Problem with libav I think

### ISSUE THREAD

**Issue by IslandRhythms** [AnIdiotsGuide/discordjs-bot-guide#124]
sudo apt-get install libav-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Package 'libav-tools' has no installation candidate

If I'm reading this correctly, does that mean I don't need libav tools as ffmpeg is now preferred? I'm on a raspberry pi model 3B+ on buster.

**Comment by Porbei** [comment]
wat

**Comment by YorkAARGH** [comment]
I honestly wouldn't know @IslandRhythms, it has been such a hot minute since I've tried anything with my raspberry pi, I would try googling your error as that seems to be (currently) outside the scope of the guide as it is currently written.
