### ISSUE TITLE
no reply

### ISSUE THREAD

**Issue by camckee316** [AnIdiotsGuide/discordjs-bot-guide#125]
copy /pasted your code got the bot online but it does not reply. what am i not doing correctly

**Comment by sewek333** [comment]
Yea,
Error: Cannot find module 'discord.js'

**Comment by YorkAARGH** [comment]
@camckee316 You will need to expand on what you have done, but I would honestly recommend you join the server there is an invite at the top of the org page, and on the guide.

Feel free to read this @sewek333 
[Getting Started - Long Version](https://anidiots.guide/getting-started/getting-started-long-version)

**Comment by eslachance** [comment]
This repository is for updates and suggestions about the guide, not for tech support. For technical support please join our Discord Guild: [https://discord.gg/4NE4bk7](https://discord.gg/4NE4bk7)
