### ISSUE TITLE
Make guild.roles.find guild.roles.cache.find in documentation

### ISSUE THREAD

**Issue by PaulRdi** [AnIdiotsGuide/discordjs-bot-guide#127]
Just got confused because the documentation isnt up to date here. Wanted to save others the hassle.

https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/understanding/roles.md

**Comment by almeidx** [comment]
Fixed in #128

**Comment by YorkAARGH** [comment]
Closing this as it's already been done in #128
