### ISSUE TITLE
Kick and ban

### ISSUE THREAD

**Issue by matthiaswuyts** [AnIdiotsGuide/discordjs-bot-guide#134]
Can you pls make one about kick and ban

**Comment by ShudhanshuSingh** [comment]
Yes I was working on it, I have submitted the pull request for the same😁.

**Comment by eslachance** [comment]
You don't need a guide to tell you how to use `GuildMember.kick()` and `GuildMember.ban()`, they are both very well documented in the discord.js documentation, *with* examples.
