### ISSUE TITLE
Hmmm

### ISSUE THREAD

**Issue by SpecialSenko** [AnIdiotsGuide/discordjs-bot-guide#152]
Do heroku no work with it?
Hmmm do the command outdated... Hmmmm HMMMMMMM mMMm mMmmmMm

**Comment by YorkAARGH** [comment]
I'm trying to see what the point of this issue is...

**Comment by SpecialSenko** [comment]
> I'm trying to see what the point of this issue is...

Well I did try the set activity and hmmm it did not work the well I wonder what is missing hmmm

**Comment by YorkAARGH** [comment]
So instead of reporting the problem you decided to basically meme in the issue tracker...

**Comment by jajamorgan** [comment]
No.
