### ISSUE TITLE
How To Reset Database Scores guild better-sqlite3 

### ISSUE THREAD

**Issue by Perdition0** [AnIdiotsGuide/discordjs-bot-guide#157]
How To Reset Database Scores guild?

im ues sql.prepare("DELETE FROM scores WHERE guild = ${message.guild.id}")

Error: SqliteError: no such table scores

**Comment by Perdition0** [comment]
Im ues better-sqlite3

**Comment by eslachance** [comment]
Sounds like your table isn't named "scores". However, the example provided in the guide is just that - an example. If you need help with databases and general javascript, please don't hesitate to ask on <https://discord.gg/code> or <https://discord.gg/programming>
