### ISSUE TITLE
Does this actually get the role object or does it just check if the role exists ?

### ISSUE THREAD

**Issue by derpr** [AnIdiotsGuide/discordjs-bot-guide#159]
```
// get role by name
let myRole = message.guild.roles.cache.find(role => role.name === "Moderators");
```
From my understanding, this doesn't get a role object. The find method just returns a boolean value of the role's existence.

**Comment by iShibi** [comment]
`Collection#find` returns the first value from the collection for which the function you provided returns true, so in the above case `myRole` will be a role object (or undefined). There is `Colection#some` which does exactly what you're talking about. See this to learn about [Collection](https://discord.js.org/#/docs/collection/master/class/Collection) methods.
