### ISSUE TITLE
Tracking Used Invites - Problem

### ISSUE THREAD

**Issue by Akira13345** [AnIdiotsGuide/discordjs-bot-guide#164]
Hi, I'm trying to get this code snippet to work today. I have encountered an error that I have solved (https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/tracking-used-invites.md)

client.guilds.forEach(g => {          ---->   client.guilds.cache.forEach(g => {

This solved my first mistake
However when I invite another member I get this error 

https://hastebin.com/obugufuqox.sql

Thank you for your help, good day to you

**Comment by YorkAARGH** [comment]
1) This isn't the place to get support with your bot, please join the server.
2) Temporary invites may be causing this issue.

**Comment by Akira13345** [comment]
Can I have the discord?
