### ISSUE TITLE
Manage events

### ISSUE THREAD

**Issue by adrianmartinezud** [AnIdiotsGuide/discordjs-bot-guide#177]
Hello, I have seen that discord has added a new function to create events and I would like to know if discordjs has something to manage this via bot, I have been looking in the documentation and I have not found anything: /

![image](https://user-images.githubusercontent.com/91871612/141760061-9a8d630c-0633-474d-ab10-a13519373713.png)

**Comment by YorkAARGH** [comment]
It's safe to assume that if it isn't in the documentation it hasn't been added __yet__, if I know the devs they're probably working on it as we speak.

**Comment by RealShadowNova** [comment]
There is a PR already opened for it https://github.com/discordjs/discord.js/pull/6493
