### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by davidlol01** [AnIdiotsGuide/discordjs-bot-guide#189]
It keeps saying invalid token while i checked the token and i'm sure it's valid
my index.js looks like this.

const { Client,  Intents } = require("discord.js");
const client = new Client({
  intents: [Intents.FLAGS.GUILDS, Intents.FLAGS.GUILD_MESSAGES]
});
const config = require("./config.json");

// Set the prefix
client.on("messageCreate", (message) => {
    if (!message.content.startsWith(config.prefix) || message.author.bot) return;
  
    if (message.content.startsWith(`${config.prefix}ping`)) {
      message.channel.send("pong!");
    } else
  
    if (message.content.startsWith(`${config.prefix}foo`)) {
      message.channel.send("bar!");
    }
  });

client.login("config.token");

**Comment by ibexzDev** [comment]
remove the quotes from the client.login() its trying to login to a token of config.token not the token at config.token's destination 


idk if you have figured it out or not but worth tryna help

**Comment by YorkAARGH** [comment]
Unknown if this was resolved or not, closing the issue.
