### ISSUE TITLE
Client Intents still supported?

### ISSUE THREAD

**Issue by seanwendt** [AnIdiotsGuide/discordjs-bot-guide#192]
I'm just trying to get the getting started bot up and running, but it doesn't seem like it recognizes the Intents import anymore.  I checked Discord.js and all I could find were examples of `GatewayIntentBits `.  Has it been deprecated?

**Comment by WilsontheWolf** [comment]
Hey there. 

Our guide is still running on discord.js v13. The latest discord.js is v14. They changed how intents work. 

You can either downgrade your discord.js using `npm i discord.js@13` or you can follow this guide on migration to fix any issues you have. <https://discordjs.guide/additional-info/changes-in-v14.html>

For additional support, you can ask in our support sever. The GitHub issue tracker is more so for issues with the guide. https://discord.gg/vXVxsAjSMF

**Comment by seanwendt** [comment]
Thank you very much for the quick response, and also for this incredible guide.  Downgrading worked.
