### ISSUE TITLE
A Basic Command Handler discord is undefined 

### ISSUE THREAD

**Issue by FisbanRegner** [AnIdiotsGuide/discordjs-bot-guide#193]
client.commands = new Discord.Collection();  <-- this line throws error Discord is undefined. 
did you mean 
client.commands = new Collection();

**Comment by Banaanae** [comment]
This guide has been written for older version of Discord.js (I believe v12)
https://discordjs.guide/ is for v14 (latest)

**Comment by prosilentgamer2** [comment]
4 months later lol

**Comment by YorkAARGH** [comment]
> This guide has been written for older version of Discord.js (I believe v12) https://discordjs.guide/ is for v14 (latest)

We're trying to get it updated but most of the staff are either burned out, or moved on from d.js.

**Comment by YorkAARGH** [comment]
> client.commands = new Discord.Collection(); <-- this line throws error Discord is undefined. did you mean client.commands = new Collection();

You would be correct, I can only apologise that I didn't respond sooner, it should be fixed in the next update!
