### ISSUE TITLE
windows-build-tools installation

### ISSUE THREAD

**Issue by olismith1** [AnIdiotsGuide/discordjs-bot-guide#37]
when i try to install windows-build-tools it doesn't install, it says please wait this may take a while. I waited 3hrs and nothing happened. Please help me

**Comment by Excigma** [comment]
Hello there,
This isn't a issue with the guide itself, but rather an issue with something going wrong while following the guide, please join our server here:  https://discord.gg/4NE4bk7 and we will be glad to help.

**Comment by YorkAARGH** [comment]
@olismith1 as @ExcigmaBot correctly stated, this isn't an issue with the guide, this is more of an internet connection / software issue, by all means join the server and we will try to help you the best we can.

**Comment by YorkAARGH** [comment]
Closing this due to no response after 12 days.
