### ISSUE TITLE
export data/value for client.user.setActivity is it possible?

### ISSUE THREAD

**Issue by Owned67** [AnIdiotsGuide/discordjs-bot-guide#62]
`if(message.content.startsWith('status')){
                              sent = new Array()
                              channel = message.channel
                               for(let sv of servers){
            // GET INITIAL DATA TO SEND MESSAGES, 
            // THEN AFTER SENDING TRIGGER THE EDIT LOOP
            let promise = getInfo(sv[0], sv[1])
            promise.then(x => {
                let info = {
                    name: x.name,
                    map: x.map,
                    pl: x.raw.numplayers,
				    fps: x.raw.rules.fps,
				    fpsavg: x.raw.rules.fps_avg,
				    maxpl: x.maxplayers
                }
                embed = createEmbed(info, sv, true)
                // msgs.add(await message.channel.send({embed}))
                message.channel.send({ embed }).then(c => {
					sent.push(c)
                    console.log('Created', c.id)
                })
                
                // msg.catch(e => console.log(e, 'ERROR SENDING EMBED-----------'))
               
            }).catch(e => {
				embed = createEmbed([], sv, false)
                // msgs.add(await message.channel.send({embed}))
                message.channel.send({ embed }).then(c => {
                    sent.push(c)
                    console.log('Created', c.id)
                })
                console.error("120:" + e + ' @ ' + sv)
            })
            
       }`

I need to get:
 `
  client.on("ready", () => {
  client.user.setActivity(`${info.pl}/${info.maxpl}`);
  });
`

I'm new on js script, can you explaim me how to get my request please?

**Comment by YorkAARGH** [comment]
Please explain what you're trying to achieve with this code.

**Comment by Owned67** [comment]
It solved but thanks :)
