### ISSUE TITLE
Auditlog doesn't work properly

### ISSUE THREAD

**Issue by Owned67** [AnIdiotsGuide/discordjs-bot-guide#69]
`let user;
    if (entry.extra.channel.id === message.channel.id
      && (entry.target.id === message.author.id)
      && (entry.createdTimestamp > (Date.now() - 5000))
      && (entry.extra.count >= 1)) {
    user = entry.executor.username
  } else { 
    user = message.author.username
  } `

${user} return a bad value sometimes... (wrong user)

can you fix it please?

**Comment by YorkAARGH** [comment]
Do you have a screenshot?

**Comment by eslachance** [comment]
Please join https://discord.gg/4NE4bk7 for any further help with this issue.
