### ISSUE TITLE
There is no console.log there

### ISSUE THREAD

**Issue by Yamgirly** [AnIdiotsGuide/discordjs-bot-guide#79]
![image](https://user-images.githubusercontent.com/37413895/70537526-71cd2b00-1bc5-11ea-9b86-27693e2db88e.png)

**Comment by ItzSudhan** [comment]
after `client.login("SuperSecretBotTokenHere");`
add this
`console.log("Bot logged in to discord.");`

**Comment by WilsontheWolf** [comment]
I believe its meant to be the setActivity
