### ISSUE TITLE
Update Audit Logger

### ISSUE THREAD

**Issue by kaanakduman** [AnIdiotsGuide/discordjs-bot-guide#85]
Hey, could you update https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/using-audit-logs.md to show how to do the same thing for 12.0.0, please?

**Comment by WilsontheWolf** [comment]
the guide still needs to be updated to v12

**Comment by YorkAARGH** [comment]
The entire guide will need to be updated to version 12, so this will be updated in turn.
